"use client"

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <Header />
      
      <section className="pt-32 pb-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Terms of <span className="gradient-text">Service</span>
          </h1>
          <p className="text-muted-foreground mb-8">Last updated: January 18, 2026</p>
          
          <div className="prose dark:prose-invert max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">1. Agreement to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                By accessing or using Nairi, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this platform.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">2. Use License</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Permission is granted to temporarily access and use Nairi for personal or commercial purposes, subject to the following conditions:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>You must not use the service for any illegal or unauthorized purpose</li>
                <li>You must not attempt to gain unauthorized access to any part of the service</li>
                <li>You must not use the service to generate harmful, misleading, or malicious content</li>
                <li>You must not resell or redistribute the service without authorization</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">3. User Accounts</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                When you create an account with us, you must provide accurate, complete, and current information. You are responsible for:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized use</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">4. Content Ownership</h2>
              <h3 className="text-xl font-medium text-foreground mb-3 mt-6">4.1 Your Content</h3>
              <p className="text-muted-foreground leading-relaxed">
                You retain ownership of content you create using Nairi. By using our service, you grant us a limited license to process and display your content as necessary to provide the service.
              </p>
              
              <h3 className="text-xl font-medium text-foreground mb-3 mt-6">4.2 Generated Content</h3>
              <p className="text-muted-foreground leading-relaxed">
                Content generated by Nairi AI in response to your prompts belongs to you, subject to these terms and any applicable third-party rights.
              </p>
              
              <h3 className="text-xl font-medium text-foreground mb-3 mt-6">4.3 Marketplace Content</h3>
              <p className="text-muted-foreground leading-relaxed">
                Content sold on the Nairi Marketplace is subject to the specific license terms set by the creator. Purchases grant you the rights specified in each item&apos;s license.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">5. Prohibited Uses</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">You agree not to use Nairi to:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Generate content that is illegal, harmful, threatening, or discriminatory</li>
                <li>Impersonate any person or entity</li>
                <li>Interfere with or disrupt the service or servers</li>
                <li>Attempt to bypass any security measures</li>
                <li>Collect user data without consent</li>
                <li>Generate spam or unsolicited communications</li>
                <li>Create content that infringes intellectual property rights</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">6. Credits and Payments</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Nairi operates on a credit-based system. By subscribing to a paid plan:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>You agree to pay all applicable fees</li>
                <li>Unused credits do not roll over unless specified</li>
                <li>Refunds are provided according to our refund policy</li>
                <li>Prices may change with reasonable notice</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">7. AI Limitations</h2>
              <p className="text-muted-foreground leading-relaxed">
                Nairi uses artificial intelligence that may produce inaccurate, incomplete, or biased results. You acknowledge that AI-generated content should be reviewed and verified before relying on it for important decisions.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">8. Disclaimer of Warranties</h2>
              <p className="text-muted-foreground leading-relaxed">
                Nairi is provided &quot;as is&quot; and &quot;as available&quot; without any warranties, expressed or implied. We do not guarantee that the service will be uninterrupted, secure, or error-free.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">9. Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">
                To the maximum extent permitted by law, Nairi and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">10. Termination</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may terminate or suspend your account and access to the service immediately, without prior notice, for any breach of these Terms. Upon termination, your right to use the service will cease immediately.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">11. Changes to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to modify these terms at any time. We will provide notice of significant changes. Continued use of the service after changes constitutes acceptance of the new terms.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">12. Contact</h2>
              <p className="text-muted-foreground leading-relaxed">
                For questions about these Terms of Service, please contact us at legal@nairi.ai or through our Contact page.
              </p>
            </section>
          </div>
        </div>
      </section>
      
      <Footer />
    </main>
  )
}
