/**
 * Email validation and tempmail detection
 * Protects against disposable email abuse
 */

// Common disposable email domains (top 200+)
const DISPOSABLE_EMAIL_DOMAINS = new Set([
  // Popular tempmail services
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  'tempmail.com', 'tempmail.net', 'temp-mail.org', 'temp-mail.io',
  'guerrillamail.com', 'guerrillamail.org', 'guerrillamail.net', 'guerrillamail.biz',
  'mailinator.com', 'mailinator.net', 'mailinator.org',
  'throwaway.email', 'throwawaymail.com',
  'fakeinbox.com', 'fakemailgenerator.com',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'dispostable.com', 'disposablemail.com',
  'getnada.com', 'nada.email',
  'mohmal.com', 'mohmal.im',
  'emailondeck.com',
  'tempail.com',
  'tempr.email',
  'discard.email',
  'discardmail.com',
  'spamgourmet.com',
  'mytrashmail.com',
  'trashmail.com', 'trashmail.net', 'trashmail.org',
  'mailnesia.com',
  'maildrop.cc',
  'getairmail.com',
  'mintemail.com',
  'tempinbox.com',
  'sharklasers.com',
  'spam4.me',
  'grr.la',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam.la',
  'binkmail.com',
  'safetymail.info',
  'spamfree24.org',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamobox.com',
  'tempomail.fr',
  'tmpmail.org',
  'tmpmail.net',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'emailfake.com',
  'fakemailgenerator.net',
  'crazymailing.com',
  'tempsky.com',
  'inboxkitten.com',
  'mailsac.com',
  'burnermail.io',
  'mailcatch.com',
  'mailnull.com',
  'mailslurp.com',
  'receivemail.com',
  'spambox.us',
  'tempmailaddress.com',
  'throwam.com',
  'tmpbox.net',
  'trbvm.com',
  'trbvn.com',
  'veryrealemail.com',
  'zmail.com',
  // Additional domains found during testing
  'dnsclick.com',
  'nesopf.com',
  'tmpmail.com',
  'emailna.co',
  'emailna.life',
  'emlhub.com',
  'emlpro.com',
  'emltmp.com',
  'fexbox.org',
  'fexbox.ru',
  'fexpost.com',
  'fextemp.com',
  'findu.pl',
  'fixmail.tk',
  'flymail.tk',
  'freemail.ms',
  'getmails.eu',
  'guerrillamail.de',
  'harakirimail.com',
  'hmamail.com',
  'imgof.com',
  'imgv.de',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'infocom.zp.ua',
  'instant-mail.de',
  'instantemailaddress.com',
  'jetable.org',
  'kasmail.com',
  'kaspop.com',
  'keepmymail.com',
  'killmail.com',
  'killmail.net',
  'klzlv.com',
  'kostenlosemailadresse.de',
  'kurzepost.de',
  'lawlita.com',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lol.ovpn.to',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lovemeleaveme.com',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'm4ilweb.info',
  'maboard.com',
  'mail-hierarchie.net',
  'mail-temporaire.fr',
  'mail.by',
  'mail.mezimages.net',
  'mail.zp.ua',
  'mail114.net',
  'mail2rss.org',
  'mail333.com',
  'mail4trash.com',
  'mailbidon.com',
  'mailblocks.com',
  'mailcatch.com',
  'mailde.de',
  'mailde.info',
  'maildrop.cc',
  'maildrop.cf',
  'maildrop.ga',
  'maildrop.gq',
  'maildrop.ml',
  'maildu.de',
  'maileater.com',
  'mailed.in',
  'mailexpire.com',
  'mailfa.tk',
  'mailforspam.com',
  'mailfree.ga',
  'mailfree.gq',
  'mailfree.ml',
  'mailfreeonline.com',
  'mailguard.me',
  'mailhazard.com',
  'mailhazard.us',
  'mailhz.me',
  'mailimate.com',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.co.uk',
  'mailinator.info',
  'mailinator.us',
  'mailinator2.com',
  'mailincubator.com',
  'mailismagic.com',
  'mailjunk.cf',
  'mailjunk.ga',
  'mailjunk.gq',
  'mailjunk.ml',
  'mailjunk.tk',
  'mailmate.com',
  'mailme.gq',
  'mailme.ir',
  'mailme.lv',
  'mailme24.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailorg.org',
  'mailpick.biz',
  'mailproxsy.com',
  'mailquack.com',
  'mailrock.biz',
  'mailsac.com',
  'mailscrap.com',
  'mailseal.de',
  'mailshell.com',
  'mailsiphon.com',
  'mailslapping.com',
  'mailslite.com',
  'mailspam.xyz',
  'mailspeed.ru',
  'mailstache.com',
  'mailtemp.info',
  'mailtome.de',
  'mailtothis.com',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailzilla.com',
  'mailzilla.org',
  'makemetheking.com',
  'manifestgenerator.com',
  'manybrain.com',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'mierdamail.com',
  'migmail.pl',
  'migumail.com',
  'mintemail.com',
  'mjukgansen.nu',
  'moakt.com',
  'moakt.ws',
  'mobileninja.co.uk',
  'moburl.com',
  'mohmal.com',
  'mohmal.im',
  'mohmal.in',
  'mohmal.tech',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'monumentmail.com',
  'ms9.mailslite.com',
  'msa.minsmail.com',
  'msb.minsmail.com',
  'msg.mailslite.com',
  'mspeciosa.com',
  'mswork.ru',
  'mt2009.com',
  'mt2014.com',
  'mt2015.com',
  'myalias.pw',
  'mycleaninbox.net',
  'myemailboxy.com',
  'mymail-in.net',
  'mymailoasis.com',
  'mynetstore.de',
  'mypacks.net',
  'mypartyclip.de',
  'myphantomemail.com',
  'mysamp.de',
  'myspaceinc.com',
  'myspaceinc.net',
  'myspacepimpedup.com',
  'myspamless.com',
  'mytempemail.com',
  'mytempmail.com',
  'mytrashmail.com',
  'nabuma.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtmansen.de',
  'netmails.com',
  'netmails.net',
  'netzidiot.de',
  'neverbox.com',
  'nice-4u.com',
  'nincsmail.hu',
  'nmail.cf',
  'nobulk.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.pw',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'nospamthanks.info',
  'notmailinator.com',
  'nowhere.org',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'nwldx.com',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'ohaaa.de',
  'omail.pro',
  'oneoffemail.com',
  'onewaymail.com',
  'onlatedotcom.info',
  'online.ms',
  'oopi.org',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'privacy.net',
  'privatdemail.net',
  'privy-mail.com',
  'privymail.de',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'putthisinyourspamdatabase.com',
  'pwrby.com',
  'qisdo.com',
  'qisoa.com',
  'quickinbox.com',
  'quickmail.nl',
  'rainmail.biz',
  'rcpt.at',
  're-gister.com',
  'reallymymail.com',
  'realtyalerts.ca',
  'recode.me',
  'recursor.net',
  'recyclemail.dk',
  'regbypass.com',
  'regbypass.comsafe-mail.net',
  'rejectmail.com',
  'reliable-mail.com',
  'remail.cf',
  'remail.ga',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'sayawaka-dea.info',
  'saynotospams.com',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'secure-mail.biz',
  'secure-mail.cc',
  'selfdestructingmail.com',
  'senseless-entertainment.com',
  'server.ms.selfip.net',
  'sharklasers.com',
  'shieldemail.com',
  'shiftmail.com',
  'shitmail.me',
  'shitmail.org',
  'shortmail.net',
  'shut.name',
  'shut.ws',
  'sibmail.com',
  'sinnlos-mail.de',
  'siteposter.net',
  'skeefmail.com',
  'slaskpost.se',
  'slopsbox.com',
  'slowslow.de',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'sneakmail.de',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'softpls.asia',
  'sogetthis.com',
  'sohu.com',
  'soisz.com',
  'solvemail.info',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamail.de',
  'spamarrest.com',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.net',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgoes.in',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamsalad.in',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spikio.com',
  'spoofmail.de',
  'squizzy.de',
  'ssoia.com',
  'startkeys.com',
  'stinkefinger.net',
  'stop-my-spam.cf',
  'stop-my-spam.com',
  'stop-my-spam.ga',
  'stop-my-spam.ml',
  'stop-my-spam.tk',
  'streetwisemail.com',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'svk.jp',
  'sweetxxx.de',
  'tafmail.com',
  'tagyourself.com',
  'talkinator.com',
  'tapchicuoihoi.com',
  'techemail.com',
  'techgroup.me',
  'teewars.org',
  'teleosaurs.xyz',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.de',
  'temp-mail.org',
  'temp-mail.ru',
  'temp.emeraldwebmail.com',
  'temp.headstrong.de',
  'tempail.com',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.co.za',
  'tempemail.com',
  'tempemail.net',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.co',
  'tempmail.de',
  'tempmail.eu',
  'tempmail.it',
  'tempmail.net',
  'tempmail.us',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempmailid.com',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'tempthe.net',
  'tempymail.com',
  'thanksnospam.info',
  'thankyou2010.com',
  'thc.st',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'thismail.net',
  'thismail.ru',
  'throam.com',
  'throwam.com',
  'throwawayemailaddress.com',
  'throwawaymail.com',
  'tilien.com',
  'tittbit.in',
  'tmailinator.com',
  'tmail.ws',
  'tmails.net',
  'tmpbox.net',
  'tmpjr.me',
  'tmpmail.net',
  'tmpmail.org',
  'toiea.com',
  'tokenmail.de',
  'tonymanso.com',
  'toomail.biz',
  'topranklist.de',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash-mail.ga',
  'trash-mail.gq',
  'trash-mail.ml',
  'trash-mail.tk',
  'trash2009.com',
  'trash2010.com',
  'trash2011.com',
  'trashbox.eu',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'trbvn.com',
  'trialmail.de',
  'trickmail.net',
  'trillianpro.com',
  'tryalert.com',
  'turual.com',
  'twinmail.de',
  'twoweirdtricks.com',
  'tyldd.com',
  'ubismail.net',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'valemail.net',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'viralplays.com',
  'vkcode.ru',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'webm4il.info',
  'webuser.in',
  'wee.my',
  'weg-werf-email.de',
  'wegwerf-email-addressen.de',
  'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wetrainbayarea.com',
  'wetrainbayarea.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whopy.com',
  'whtjddn.33mail.com',
  'whyspam.me',
  'wilemail.com',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wolfsmail.tk',
  'wollan.info',
  'worldspace.link',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.co',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.gq',
  'yopmail.net',
  'you-spam.com',
  'yourdomain.com',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoaxe.com',
  'zoemail.com',
  'zoemail.net',
  'zoemail.org',
  'zomg.info',
  'zxcv.com',
  'zxcvbnm.com',
  'zzz.com',
])

// Suspicious domain patterns
const SUSPICIOUS_PATTERNS = [
  /^temp/i,
  /^fake/i,
  /^trash/i,
  /^spam/i,
  /^disposable/i,
  /^throwaway/i,
  /^guerrilla/i,
  /^mailinator/i,
  /^yopmail/i,
  /^10minute/i,
  /mail.*temp/i,
  /temp.*mail/i,
  /^junk/i,
  /^burner/i,
]

export interface EmailValidationResult {
  isValid: boolean
  isDisposable: boolean
  reason?: string
}

/**
 * Validate email and check if it's a disposable/tempmail address
 */
export function validateEmail(email: string): EmailValidationResult {
  // Basic email format validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailRegex.test(email)) {
    return {
      isValid: false,
      isDisposable: false,
      reason: 'Invalid email format'
    }
  }

  const domain = email.split('@')[1].toLowerCase()

  // Check against known disposable domains
  if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) {
    return {
      isValid: false,
      isDisposable: true,
      reason: 'Disposable email addresses are not allowed. Please use a permanent email address.'
    }
  }

  // Check against suspicious patterns
  for (const pattern of SUSPICIOUS_PATTERNS) {
    if (pattern.test(domain)) {
      return {
        isValid: false,
        isDisposable: true,
        reason: 'This email domain appears to be a temporary email service. Please use a permanent email address.'
      }
    }
  }

  // Check for very short or suspicious TLDs
  const tld = domain.split('.').pop()
  const suspiciousTLDs = ['tk', 'ml', 'ga', 'cf', 'gq'] // Free TLDs often used for spam
  if (tld && suspiciousTLDs.includes(tld.toLowerCase())) {
    // Not blocking, but flagging for review
    console.warn(`[Email Validation] Suspicious TLD detected: ${domain}`)
  }

  return {
    isValid: true,
    isDisposable: false
  }
}

/**
 * Check if email domain has valid MX records (async)
 * This is a more thorough check but requires DNS lookup
 */
export async function validateEmailDomain(email: string): Promise<boolean> {
  // In browser/edge runtime, we can't do DNS lookups
  // This would need to be done server-side with Node.js dns module
  // For now, return true and rely on the domain blacklist
  return true
}

export { DISPOSABLE_EMAIL_DOMAINS }
